# db_connection.py
#THE FOLLOWING CODE WAS DONE ONLY FOR CHECKING THE COMMIT IN GITHUB. IT IS NOT PART OF THE ACTUAL APPLICATION. PLEASE IGNORE THIS CODE.
import pyodbc

'''THIS FILE ESTABLISHES A CONNECTION TO THE SQL SERVER DATABASE USING PYODBC. IT DEFINES A CONNECTION OBJECT THAT CAN BE IMPORTED AND USED IN OTHER PARTS OF THE APPLICATION TO INTERACT WITH THE DATABASE.
THE CONNECTION IS DRAFTED WITH PLACEHOLDER VALUES FOR THE SERVER NAME, DATABASE NAME, USERNAME, AND PASSWORD. 
THESE SHOULD BE REPLACED WITH THE ACTUAL CREDENTIALS TO CONNECT TO THE DATABASE.
'''

conn = pyodbc.connect(
    "DRIVER={SQL Server};"
    "SERVER=SERVER_NAME;"
    "DATABASE=DATABASE_NAME;"
    "UID=Career26Flow;"
    "PWD=strongPasword"
)